from tkinter import *
import tkinter.font as tkFont
root=Tk()
root.title("PYTHON PROJECT")
root['bg'] = 'white'
root.geometry("400x400")
fontStyle = tkFont.Font( size=30)
fontStyle1 = tkFont.Font( size=20)
label0=Label(root,text="WELCOME TO SOV TOURS AND TRAVELS", width = 50, bg='blue',fg='black', font=fontStyle)
label0.place(x=100, y= 10)
label1=Label(root,text="enter Name : ", font = fontStyle1, bg='red' )
label1.place(y=70)
label2=Label(root,text="Starting City :", font = fontStyle1,bg='red')
label2.place(y=120)
label3=Label(root,text="Gender :", font = fontStyle1,bg='red')
label3.place(y=180)
var6 = IntVar()
c6=Radiobutton(root, text="MALE", variable=var6, font = fontStyle1 , value=1, bg='blue',fg='black')
c6.place(x=150, y = 180)
c7=Radiobutton(root, text="FEMALE", variable=var6, font = fontStyle1 , value=2, bg='blue',fg='black')
c7.place(x=280, y = 180)
c8=Radiobutton(root, text="OTHER", variable=var6, font = fontStyle1 , value=3, bg='blue',fg='black')
c8.place(x=445, y = 180)
entry1=Entry(root, width = 50, font = fontStyle1)
entry1.place(x=170, y = 70)
var1 = IntVar()
c1=Radiobutton(root, text="MUMBAI", variable=var1, font = fontStyle1, value=1, bg='blue',fg='black')
c1.place(x=180, y = 120)
c2=Radiobutton(root, text="DELHI", variable=var1, font = fontStyle1,value=2, bg='blue',fg='black')
c2.place(x=320, y = 120)
c3=Radiobutton(root, text="HYDERABAD", variable=var1, font = fontStyle1, value=3, bg='blue',fg='black')
c3.place(x=435, y = 120)
c4=Radiobutton(root, text="JAIPUR", variable=var1, font = fontStyle1, value=4, bg='blue',fg='black')
c4.place(x=635, y = 120)
c5=Radiobutton(root, text="AHMEDABAD", variable=var1, font = fontStyle1, value=5, bg='blue',fg='black')
c5.place(x=760, y = 120)